# Generated by Django 4.2.2 on 2024-01-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=500)),
                ('viewed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='static/img')),
            ],
        ),
        migrations.CreateModel(
            name='TeamOnSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/img')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('comment', models.CharField(max_length=500)),
                ('service', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
    ]
